[package]
name        = "bip_utracker"
version     = "0.0.2"
description = "Communication with bittorrent UDP trackers"

authors     = ["Andrew <amiller4421@gmail.com>"]

homepage    = "https://github.com/GGist/bip-rs/bip_utracker"
repository  = "https://github.com/GGist/bip-rs/bip_utracker"

keywords    = ["tracker", "bittorrent", "udp"]

license     = "MIT/Apache-2.0"

[features]
unstable = []