language: rust
rust:
  - stable
  - beta
  - nightly

sudo: false

env:
  matrix:
    - CRATE_DIR=bip
    - CRATE_DIR=bip_bencode
    - CRATE_DIR=bip_dht
    - CRATE_DIR=bip_disk
    - CRATE_DIR=bip_handshake
    - CRATE_DIR=bip_htracker
    - CRATE_DIR=bip_lpd
    - CRATE_DIR=bip_magnet
    - CRATE_DIR=bip_metainfo
    - CRATE_DIR=bip_peer
    - CRATE_DIR=bip_util
    - CRATE_DIR=bip_utracker
    
branches:
  only:
    - master
