language: rust
rust: nightly
env: FEATURES="--features nightly"

sudo: true

env:
  global:
    - secure: cBgN6D8ZxwC5UA+3pxWg8ZHf1rtnEPEbwYP9W+NNzzOGLXDvDsZVhBeP0v9ZSHOdIxAENk5zypJOgV3TnMAk/JT5+oJ4elNJfefi22Mxlj5PRANb8K894nBXAzhgEB1LFfOh/9gSrvOZzbmK35l8fGFUx263BqcoPIjQ4UEcuyo=

branches:
  only:
    - master 

script:
  - cargo build
  - cargo test
  - cargo doc

after_success:
  # Generate And Publish Documentation
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "travis-ci"
  - git clone --quiet --branch=gh-pages https://${GH_TOKEN}@github.com/GGist/redox-rs gh-pages > /dev/null
  - cd gh-pages
  - mv ./index.html ../target/doc
  - rm -rf ./*
  - cp -rf ../target/doc/* .
  - git add -A
  - git commit -m "Latest rustdoc on successful travis build $TRAVIS_BUILD_NUMBER auto-pushed to gh-pages"
  - git push -fq origin gh-pages > /dev/null
  - cd ..
  # Generate And Publish Test Coverage
  - sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev
  - wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz
  - tar xzf master.tar.gz
  - mkdir kcov-master/build && cd kcov-master/build
  - cmake .. && make
  - sudo make install && cd ../..
  - kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/redox-*