os: Visual Studio 2015

environment:
  RUSTUP_USE_HYPER: 1
  CARGO_HTTP_CHECK_REVOKE: false

  matrix:
  - CRATE_DIR: bip_bencode
    TARGET: i686-pc-windows-msvc

  - CRATE_DIR: bip_dht
    TARGET: i686-pc-windows-msvc

  - CRATE_DIR: bip_disk
    TARGET: i686-pc-windows-msvc

  - CRATE_DIR: bip_handshake
    TARGET: i686-pc-windows-msvc

  - CRATE_DIR: bip_htracker
    TARGET: i686-pc-windows-msvc

  - CRATE_DIR: bip_lpd
    TARGET: i686-pc-windows-msvc

  - CRATE_DIR: bip_magnet
    TARGET: i686-pc-windows-msvc

  - CRATE_DIR: bip_metainfo
    TARGET: i686-pc-windows-msvc

  - CRATE_DIR: bip_peer
    TARGET: i686-pc-windows-msvc

  - CRATE_DIR: bip_util
    TARGET: i686-pc-windows-msvc

  - CRATE_DIR: bip_utracker
    TARGET: i686-pc-windows-msvc

install:
  - appveyor DownlaodFile https://win.rustup.rs -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain nightly --default-host %TARGET%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

build: false

test_script:
  - cd %CRATE_DIR%
  - cargo build
  - cargo test --verbose