branches:
  only:
    - master

os:
  - MinGW
  
install:
  - ps: Start-FileDownload 'https://static.rust-lang.org/dist/rust-nightly-i686-pc-windows-gnu.exe'
  - rust-nightly-i686-pc-windows-gnu.exe /VERYSILENT /NORESTART /DIR="C:\Rust"
  - SET PATH=%PATH%;C:\MinGW\bin
  - SET PATH=%PATH%;C:\Rust\bin
  - gcc --version
  - rustc -V
  - cargo -V

build_script:
  - cargo build

test_script:
  - cargo test