[package]
name        = "bip_disk"
version     = "0.1.0"
description = "Bittorrent Infrastructure Project Disk Module"

authors     = ["Andrew <amiller4421@gmail.com>"]

homepage    = "https://github.com/GGist/bip-rs/bip_disk"
repository  = "https://github.com/GGist/bip-rs/bip_disk"

keywords    = ["filesystem", "fs", "disk"]

license     = "MIT/Apache-2.0"

[dependencies]
bip_metainfo    = { version = "0.9" }
bip_util        = { version = "0.5" }
crossbeam       = "0.2"
futures         = "0.1"
futures-cpupool = "0.1"
error-chain     = "0.7"
tokio-core      = "0.1"

[dev-dependencies]
rand            = "0.3"

[features]
unstable        = []

[[test]]
name            = "test"
path            = "test/mod.rs"