[package]
name        = "bip_metainfo"
version     = "0.1.0"
description = "Parsing and building of bittorrent metainfo files"

authors     = ["Andrew <amiller4421@gmail.com>"]

homepage    = "https://github.com/GGist/bip-rs/bip_metainfo"
repository  = "https://github.com/GGist/bip-rs/bip_metainfo"

keywords    = ["metainfo", "torrent", "file", "bittorrent"]

license     = "MIT"

[dependencies]
bip_bencode = { path = "../bip_bencode", version = "0.1.0" }
bip_util    = { path = "../bip_util", version = "0.2.0" }
chrono      = "0.2.0"
memmap      = "0.2.0"
url         = "0.5.0"
walkdir     = "0.1.0"

[features]
unstable = []