[package]
name        = "bip_handshake"
version     = "0.1.1"
description = "Common handshaking interface as well as a default handshake implementation"

authors     = ["Andrew <amiller4421@gmail.com>"]

homepage    = "https://github.com/GGist/bip-rs/bip_handshake"
repository  = "https://github.com/GGist/bip-rs/bip_handshake"

keywords    = ["handshake", "bittorrent"]

license     = "MIT"

[dependencies]
bip_util    = { path = "../bip_util", version = "0.1.0" }
mio         = "0.5.0"
bytes       = "0.3.0"
log         = "0.3.0"

[features]
unstable = []